spring:
 datasource:
   username: root
   password: 123456
   url: jdbc:mysql://localhost:3306/smart_cp?useSSL=false&useUnicode=true&characterEncoding=utf-8
   driver-class-name: com.mysql.jdbc.Driver